#!/usr/bin/env lua

-- Make the SbarLua module (built via `SbarLua`'s `make install`) importable.
package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"

sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.end_config()

sbar.event_loop()
